# action.yml
name: 'kube-devops-ci'
description: 'Run the main commands to deploy or build services like kubernetes and aws using CLI.'
author: 'CodeView Consulting'
branding:
  icon: 'box'
  color: 'purple'
inputs:
  command:
    description: 'commands avaliable'
    required: true
  kubectl:
    description: 'kubectl version'
  kustomize:
    description: 'kustomize version'
  helm:
    description: 'helm version'
  helmv3:
    description: 'helm version'
  kubeseal:
    description: 'kubeseal version'
  kubeaudit:
    description: 'kubeaudit version'
  kubeval:
    description: 'kubeval version'
  kops:
    description: 'kops version'    
  terraform:
    description: 'terraform version' 
  awscli:
    description: 'aws version'          
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.kubectl }}
    - ${{ inputs.kustomize }}
    - ${{ inputs.helm }}
    - ${{ inputs.helmv3 }}
    - ${{ inputs.kubeseal }}
    - ${{ inputs.kubeval }}    
    - ${{ inputs.kops }}
    - ${{ inputs.terraform }}  
    - ${{ inputs.aws }}      