name: kube-devops-ci

on:
  push:
    branches:
      - main
  release:
    types: [published]
    
jobs:

  build_push_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: codeviewbr/kube-devops-ci
          tag_with_ref: true

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: codeviewbr/kube-devops-ci:${{ steps.tag_version.outputs.changelog }}

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: codeviewbr/kube-devops-ci:${{ steps.tag_version.outputs.changelog }}          