name: kube-devops-ci

on:
  push:
    branches:
      - main
  release:
    types: [published]
    
jobs:

  build_push_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: codeviewbr/kube-devops-ci
          tag_with_ref: true
