name: kube-devops-build-test

on: 
  pull_request:
    branches:
      - main

jobs:
  build_test_docker_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Test Build Image
        run: docker build -t kube-devops-ci:test .