  
name: Actions Examples

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo 'hello'