name: test-action

on:
  push:
    branches:
      - main

jobs:
  test-image-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set kube-ci
        uses: codeviewbr/kube-devops-ci@v0.2.1
        id: vars
        with:
          command: aws --version