name: test-manual-action

on:
  workflow_dispatch:
    inputs:
      command:
        description: Input a command valid
        default: aws --version
        required: true
      version:
        description: Input action version
        default: v0.2.64
        required: true

jobs:
  manual-action:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: kube-devops-ci
        uses: codeviewbr/kube-devops-ci@${{ github.event.inputs.version }}
        env: 
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}  
        with:
          command: ${{ github.event.inputs.command }}